version: "3"
virtualbrowsers:
- name: harness
  url: https://tinyurl.com/harness-seworkshop
virtualmachines:
- name: sandbox
  image: instruqt/docker-2010
  shell: /bin/bash
  machine_type: n2-standard-2
  allow_external_ingress:
  - http
  - https
  - high-ports
secrets:
- name: SE_WORKSHOP_PAT
- name: SE_WORKSHOP_ORG_ID
- name: SE_WORKSHOP_ACCOUNT_ID
- name: SE_WORKSHOP_USER_PWD
- name: SE_WORKSHOP_USER_GRP_ID
- name: SE_WORKSHOP_KEYCLOAK_ENDPOINT
- name: SE_WORKSHOP_KEYCLOAK_REALM
- name: SE_WORKSHOP_KEYCLOAK_ADMIN_USER
- name: SE_WORKSHOP_KEYCLOAK_ADMIN_PWD
